name: BlackClover
version: ${project.version}
main: net.dohaw.blackclover.BlackCloverPlugin
api-version: 1.16

commands:
  blackclover:
    description: "Base command for this plugin"
    aliases:
      - bc
      - blackc
      - blc
      - blclover
      - bclover

permissions:
  blackclover.set.grimmoire:
    default: op
    description: Allows a player to set grimmoires
  blackclover.set.level:
    default: op
    description: Allows a player to set a player's level
  blackclover.set.xp:
    default: op
    description: Allows a player to set a player's XP
  blackclover.set.points:
    default: op
    description: Allows a player to set a player's points
  blackclover.info.others:
    default: op
    description: Allows a player to see info about another player
  blackclover.info.self:
    default: true
    description: Allows a player to see info about themselves

